baseURL: ""
languageCode: en-us
title: brian's blog 
theme: PaperMod

params:

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
  
  homeInfoParams:
    Title: 'hello stranger'
    Content: 'welcome to my personal blog where I talk about my coding journey and some random stuff too.  A 14yr boy coding random stuff, likes playing videos games and hate studying :)'
  socialIcons:
    - name: facebook
      url: https://example.org/
    - name: instagram
      url: https://example.org/
  cover:
    linkFullimages: true

  ShowBreadCrumbs: true

  ShowReadingTime: false

  ShowShareButtons: false

  ShowPostNavLinks: true

  
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: Archives
      name: archives
      url: /archives/
      weight: 30
    - identifier: rick roll
      name: friends?
      url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      weight: 40
