baseURL: ""
languageCode: en-us
title: brianle.blog()
theme: PaperMod
googleAnalytics: "G-WGL465XVCE"



outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


params:
  editPost:
        URL: "https://github.com/iambrianle/blog"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link
  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
  
  profileMode:
        enabled: true
        title: "hi stranger" 
        subtitle: "welcome to my personal blog where I talk about my coding journey and some random stuff too. 14yr old coding enthusiast. currently studying web security and web development!  #4yearofcode "
        imageUrl: "/hecker.jpg" # optional
        imageTitle: "hecker" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
  socialIcons:
    - name: facebook
      url: https://www.facebook.com/profile.php?id=100054776811026
    - name: instagram
      url: https://www.instagram.com/briandotle/
    - name: Github
      url: https://github.com/iambrianle
    - name: Email
      url: mailto:iambrian@duck.com?


  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  Comments: true

  

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: tags
      url: /tags/
      weight: 40
    - identifier: Archives
      name: posts
      url: /archives/
      weight: 20
    - identifier: Search
      name: search
      url: /search/
      weight: 10




